version: "3.8"

services: 
  app: ## 두번째 레벨에 오는것들이 컨테이너 하나하나
    container_name: good-container
    build:
      context: .
      dockerfile: Dockerfile-app
    environment: 
      - TZ=Asia/Seoul
    ports:
      - 9999:8080
    depends_on: ## db가 먼저 실행되고 app이 실행되게 세팅 100% 확실하게 보장하지는 않는다
      - database
  
  database:
    container_name: good-db
    build:
      context: .
      dockerfile: Dockerfile-db
    hostname: docker-mysql
    ports:
      - 3307:3306
    environment: 
      MYSQL_DATABASE: ver4
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1111